#
# Copyright (C) 2015 - 2029. Hydra Project.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=Hexonwall
PKG_RELEASE:=$(AUTORELEASE)

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL=https://github.com/Kowloongs/Hexonwall.git
PKG_SOURCE_DATE:=2023-04-23
PKG_SOURCE_VERSION:=c8bb3568b47e5190d6eafc4151d1f0e9c31c3d1d
PKG_MIRROR_HASH:=skip
PKG_MAINTAINER:=Carlyon W. Tung <loongs@syuusui.com>
PKG_LICENSE:=Ombres

include $(INCLUDE_DIR)/package.mk

define Package/Hexonwall
  SECTION:=net
  CATEGORY:=Base system
  TITLE:=The Sixth Generation Firewall
  DEPENDS:=
  EXTRA_DEPENDS:=
  PROVIDES:=
endef

define Package/Hexonwall/description
 The Sixth Generation Firewall.
endef

define Package/Hexonwall/conffiles
endef

define Package/Hexonwall/install
endef

define Build/Compile
endef

$(eval $(call BuildPackage,Hexonwall))
