#!/bin/sh
#
# Copyright (C) 2015 - 2029. Hydra Project.
#

export HOTPLUG_TYPE="$1"

. /lib/functions.sh

PATH="%PATH%"
LOGNAME=root
USER=root
export PATH LOGNAME USER
export DEVICENAME="${DEVPATH##*/}"

if [ \! -z "$1" -a -d /etc/hotplug.d/$1 ]; then
	for script in $(ls /etc/hotplug.d/$1/* 2>&-); do (
		[ -f $script ] && . $script
	); done
fi
