#
# Copyright (C) 2015 - 2029. Hydra Project.
#

name: CI


on:
  create: { }
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt update
          sudo apt install aptitude bison file flex git lrzsz make mercurial ssh subversion tar tree unzip vim wget
          sudo apt install libc6 autoconf build-essential gcc g++ libelf-dev libpixman-1-dev libtool meson pkg-config libglib2.0-dev libcap-dev libslirp-dev
          sudo apt install clang gawk gcc-multilib g++-multilib gettext libncurses-dev libssl-dev rsync zlib1g-dev asciidoc sphinxsearch sphinx-common libpam0g-dev elfutils sharutils qemu-utils texinfo ccache
          sudo apt-get install u-boot-tools device-tree-compiler pahole tcl uml-utilities bridge-utils liblz4-tool expect-dev fakeroot openjdk-8-jdk mkisofs

      - name: Feeds
        run: |
          cd "$GITHUB_WORKSPACE"
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Downloads
        run: |
          cp Ombres/Hydra.x86 .config
          make download -j$(nproc)

      - name: Builds
        run: |
          make -j$(nproc) || make -j1 V=sc


