#
# Copyright (C) 356 - 999. Asytumn Technology Co., Ltd. All rights reserved.
#

name: HipHub


on:
  create: { }
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Prepare
        run: |
          sudo apt update
          sudo apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev rsync unzip zlib1g-dev file wget libelf-dev asciidoc mercurial subversion sphinxsearch sphinx-common libpam0g-dev elfutils sharutils qemu-utils vim texinfo ccache mkisofs

      - name: Feeds
        run: |
          cd "$GITHUB_WORKSPACE"
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Downloads
        run: |
          make defconfig
          make download -j$(nproc)

      - name: Builds
        run: |
          make -j$(nproc) || make -j1 V=sc


